### ISSUE TITLE
[C4GT Community]: Test ticket

### ISSUE THREAD

**Issue by karntrehan** [PSMRI/AMRIT#21]
## Description
[Provide a brief project description, outlining the need and measurable goals of the feature to be developed. Kindly, specify the number of users or scale of the product and feature, articulating its anticipated impact and intended use.]

## Goals
- [ ] [Goal 1]
- [ ] [Goal 2]
- [ ] [Goal 3]
- [ ] [Goal 4]
- [ ] [Goal 5]
- [ ] [Midpoint Milestone]
[Please also specify the Mid-point milestones- goals that must be achieved by 1.5 months into the coding period. Kindly, state and link installation guide/ set-up steps (if any) in this section]

### Expected Outcome

Test

### Implementation Details

Test

### Product Name

Test

### Organisation Name

Piramal Swasthya Management Research Institute

### Tech Skills Needed

Agile, Angular, Artificial Intelligence

### Mentor(s)

@drtechie 

### Complexity

Medium

### Category

Analytics

**Comment by Sneha6003** [comment]
https://github.com/all-contributors please add @devikasuresh20 for code
