### ISSUE TITLE
[C4GT Community]: Migrate Documentation from MkDocs to GitBook and Enhance Information Hierarchy

### ISSUE THREAD

**Issue by drtechie** [PSMRI/AMRIT#7]
### Description

We need to migrate the existing documentation for the AMRIT platform from the current MkDocs site to GitBook. The new documentation should provide a better information hierarchy, making it easier for users to navigate and find relevant information. The goal is to create a more structured, user-friendly documentation site that aligns with AMRIT's mission and future goals.

The selected contributor will collaborate closely with the AMRIT team to understand the existing documentation, identify areas for improvement, and implement a new structure in GitBook. This will involve not only moving content but also enhancing the layout, adding new sections where necessary, and ensuring the documentation is comprehensive and accessible.

#### What You Will Learn:

As a contributor, you will:
- Gain hands-on experience with GitBook and modern documentation practices.
- Develop skills in organizing and presenting technical content for diverse audiences.
- Enhance your knowledge of information architecture and content strategy.
- Learn about the healthcare technology domain and how digital public goods like AMRIT impact healthcare accessibility.
- Collaborate with a team of professionals in the public health sector and contribute to a meaningful project.

#### Desired Skills:

- Strong understanding of technical documentation tools, especially GitBook and MkDocs.
- Experience in organizing and structuring technical content for clarity and ease of use.
- Attention to detail and ability to improve the readability and accessibility of documentation.
- Good communication skills for working closely with the AMRIT team and gathering feedback.
- Familiarity with Git/GitHub for version control and collaboration.

### Goals

- [ ] Successfully migrate all existing documentation from MkDocs to GitBook.
- [ ] Reorganize the documentation structure to improve information hierarchy and user experience.
- [ ] Ensure the new documentation site is fully functional, visually appealing, and aligns with AMRIT’s branding.

### Expected Outcome

A fully migrated and improved documentation site on GitBook.
A well-structured information hierarchy that makes the documentation easy to navigate and understand.

### Acceptance Criteria

- All content from the MkDocs site is successfully migrated to GitBook.
- The new documentation structure is reviewed and approved by the AMRIT team.
- The GitBook site is fully functional, with no broken links or missing content.
- The documentation is organized in a way that is easy to navigate, with clear sections and logical flow.

### Implementation Details

- The contributor will start by reviewing the existing documentation and creating a plan for the migration and restructuring process.
- You will get access to the GitBook project and the existing content will be migrated.
- The content will be reorganized into a new structure, with sections and sub-sections as needed.
- The contributor will work with the AMRIT team to refine the content and structure, ensuring it meets the project’s goals.
- The final documentation will be tested for usability before being published.

The current documentation can be found [here](https://psmri.github.io/PSMRI/). The contributor will need to familiarize themselves with this content and work closely with the AMRIT team to ensure a smooth transition to GitBook.

### Mockups/Wireframes

NA

### Product Name

AMRIT

### Organisation Name

Piramal Swasthya Management Research Institute

### Domain

Healthcare

### Tech Skills Needed

Markdown

### Mentor(s)

@drtechie 

### Complexity

High

### Category

Documentation

**Comment by KiranBaliga** [comment]
Hi @drtechie, will this task require expert skills or someone who is genuinely interested in learning & contrubuting can work on this task with a small guidance?

**Comment by VedantKhairnar** [comment]
Hello @KiranBaliga 
Basic level of knowledge about markdown should be enough for the task. 
Markdown is easy to learn and here's a [guide](https://www.markdownguide.org/basic-syntax/) for reference.

Pls let us know if you are interested and we will assign you the issue. We will obviously guide you where ever needed.
Thanks.

**Comment by KiranBaliga** [comment]
Thank you. I would like to know if there is a urgent deadline. I have some medical committments but I can take up the issue and start working!

**Comment by drtechie** [comment]
Hi @KiranBaliga,
I moved the documentation to GitBook last week (https://piramal-swasthya.gitbook.io/amrit).
However, I still need help with documenting the developer environment setup.
I will be creating separate tickets for these. Will tag you. Thank you for your interest in contributing to AMRIT.
