### ISSUE TITLE
[C4GT Community]: Design and Develop AMRIT Website Pages - Landing, Programs

### ISSUE THREAD

**Issue by drtechie** [PSMRI/AMRIT#8]
### Ticket Contents

# [Applications closed]

## Description
AMRIT (Accessible Medical Records via Integrated Technologies) is an initiative by Piramal Swasthya to provide digital health solutions that integrate healthcare services and ensure accessible medical records. We need a website showcasing AMRIT's features, benefits, and impact. The website should cater to various stakeholders, including healthcare providers, policymakers, and the general public. It should highlight the platform's capabilities, success stories, and future goals. The website will serve as a key tool for promoting AMRIT and attracting support and collaboration.

## What you will learn

As an intern, you will:
- Gain hands-on experience with the [Astro](https://astro.build/) framework and modern web development practices.
- Develop skills in creating responsive and accessible websites.
- Enhance your knowledge of performance optimization and SEO.
- Work collaboratively with a team of experienced professionals and mentors.
- Gain insights into the healthcare technology and development sector and the impact of digital health solutions.

## Desired skills:

- Good understanding of HTML, CSS, and JavaScript.
- Keen eye for detail and meticulous in implementing designs and layouts accurately.
- Good communication skills for effective collaboration with the team.
- Shows enthusiasm for learning new technologies and frameworks.
- Comfortable using Git/GitHub for version control.

### Goals

- [ ] Clone the project and get familiarized with Astro framework and routing.
- [ ] Create pages for landing and programs supported by AMRIT

### Expected Outcome

The final product should be a fully functional and polished website that effectively showcases AMRIT. The website should have a modern and clean design, with intuitive navigation and well-organized content. It should include sections on the platform's features, benefits, success stories, and news updates. The site should be responsive and accessible.

### Acceptance Criteria

The website must score 95+ in performance and 100 in Accessibility, Best Practices and SEO in [Page Speed Insights](https://pagespeed.web.dev/).

### Implementation Details

The website will be developed using an [Astro](https://astro.build/) theme. The theme has already been forked [here](https://github.com/PSMRI/AMRIT), providing a good head start for customizing and developing the required pages.

The selected candidate will collaborate closely with mentors and team members from PSMRI. PSMRI will provide all the necessary content for the website. Regular catch-ups and brainstorming sessions will be conducted to finalize the layout and design of each page, ensuring alignment with the project's goals and branding.

### Mockups/Wireframes

The theme is based on https://pinwheel-astro.vercel.app/

### Product Name

AMRIT

### Organisation Name

Piramal Swasthya Management Research Institute 

### Domain

Healthcare

### Tech Skills Needed

Design, ESLint, HTML, JavaScript, Prettier, Tailwind CSS, UI/UX/Design

### Mentor(s)

@drtechie 

### Complexity

Medium

### Category

Documentation, Frontend, SEO

### How to apply

Please fill the [form](https://forms.gle/WXTjycH8sqXbeB4m6).

### Bounty

This is a bounty ticket with a remuneration of **INR 15,000**.

**Comment by gupta-soham** [comment]
Is this issue still open @drtechie, also can I use Next.js to implement the pages?

**Comment by Asp-Codes** [comment]
Hey @drtechie , can I take on this issue? Also, do I need to complete the form mentioned in the first comment?

**Comment by drtechie** [comment]
Closing this issue.
The website is being developed by 2 other contributors.
Ref: #5 #6

**Comment by drtechie** [comment]
@all-contributors please add @adarshnjena for code
@all-contributors please add @SanjanaSogimatt for code

**Comment by drtechie** [comment]
@all-contributors please add @SanjanaSogimatt for code
